### ISSUE TITLE
Composer install error: not match your minimum-stability.

### ISSUE THREAD

**Issue by sitiodocanoamarelo** [thunder/thunder-project#22]
I'm trying to install thunder 6 but I get the following error message upon composer install: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/search_api_mark_outdated ^1.0, found drupal/search_api_mark_outdated[dev-1.x, 1.0.0-beta1, 1.x-dev (alias of dev-1.x)] but it does not match your minimum-stability.
  Problem 2
    - Root composer.json requires thunder/thunder_performance_measurement dev-master -> satisfiable by thunder/thunder_performance_measurement[dev-master].
    - thunder/thunder_performance_measurement dev-master requires thunder/sampler dev-master -> found thunder/sampler[dev-master] but it does not match your minimum-stability.

Can anyone help ?
Thanks

**Comment by dbosen** [comment]
Hello!

Could you please describe the steps you have taken, to install Thunder?

When I do the following steps, I do not get any errors:

```
composer create-project thunder/thunder-project thunder --no-interaction --no-install
cd thunder
composer install
```

Also, which versions of PHP and composer are you using?

**Comment by sitiodocanoamarelo** [comment]
Hi Daniel,

Thank you for your fast reply.
Silly me, I forgot to "cd thunder"
Now I have another error: drupal/coder failed but going to put it in
another thread.

Cheers,

Nuno
PS: PHP 7.4, Composer 2.0.6

Daniel Bosen ***@***.***> escreveu no dia quinta, 25/03/2021
à(s) 11:43:
